### ISSUE TITLE
img2pdf not able to converty

### ISSUE THREAD

**Issue by lucas-ljb** [MiniGlome/Archive.org-Downloader#109]
C:\Users\Lucas> python "C:\Users\Lucas\Archive.org-Downloader\archive-org-downloader.py" -e "moreira2003@hotmail.ca" -p "Poopoo89!" -r 0 -u "https://archive.org/details/bibletarot0000cori/"
1 Book(s) to download
[+] Successful login
========================================
Current book: https://archive.org/details/bibletarot0000cori
[+] Successful loan
[+] Found 292 pages
Downloading pages...
100%|████████████████████████████████████████████████████████████████████████████████| 292/292 [00:24<00:00, 12.04it/s]
Traceback (most recent call last):
  File "C:\Users\Lucas\Archive.org-Downloader\archive-org-downloader.py", line 267, in <module>
    pdf = img2pdf.convert(images, **pdfmeta)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\AppData\Roaming\Python\Python312\site-packages\img2pdf.py", line 2651, in convert
    pdf = pdfdoc(
          ^^^^^^^
  File "C:\Users\Lucas\AppData\Roaming\Python\Python312\site-packages\img2pdf.py", line 742, in __init__
    v = ("D:" + datetime_to_pdfdate(v)).encode("ascii")
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\AppData\Roaming\Python\Python312\site-packages\img2pdf.py", line 725, in datetime_to_pdfdate
    return dt.astimezone(tz=timezone.utc).strftime("%Y%m%d%H%M%SZ")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

I am able to call img2pdf on cmd but when Archive downloader tries it fails

**Comment by ali7mrd** [comment]
running the "pip install -r requirements.txt" command again solved the issue fo me.

**Comment by Raradra** [comment]
I have the same issue. Unfortunately, running the "pip install -r requirements.txt" command again didn't help.

**Comment by asheroto** [comment]
Same issue here. Looksl ike the jpg images are actually downloaded, but the PDF is not created.

<details><summary>Details</summary>
<p>

```
Traceback (most recent call last):
  File "C:\tools\Archive.org-Downloader\archive-org-downloader.py", line 267, in <module>
    pdf = img2pdf.convert(images, **pdfmeta)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\img2pdf.py", line 2651, in convert
    pdf = pdfdoc(
          ^^^^^^^
  File "C:\Python312\Lib\site-packages\img2pdf.py", line 742, in __init__
    v = ("D:" + datetime_to_pdfdate(v)).encode("ascii")
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\img2pdf.py", line 725, in datetime_to_pdfdate
    return dt.astimezone(tz=timezone.utc).strftime("%Y%m%d%H%M%SZ")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
```

</p>
</details>

**Comment by asheroto** [comment]
Got it figured out in #120.

Here's a link to the fixed version:
https://github.com/asheroto/Archive.org-Downloader/blob/patch-5/archive-org-downloader.py

**Comment by dangerweenie** [comment]
> Got it figured out in [#120](https://github.com/MiniGlome/Archive.org-Downloader/pull/120).
> 
> Here's a link to the fixed version: https://github.com/asheroto/Archive.org-Downloader/blob/patch-5/archive-org-downloader.py

I cloned your fork and tried running it with the same command from the original fork and i'm getting this issue now:

`py archive-org-downloader.py -e XXXX -pXXXX -r 0 -u https://archive.org/details/BOOK_TITLE/

1 Book(s) to download
[-] Error while login:
<Response [400]>
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
</html>`

**Comment by TemplarB** [comment]
> 
> 1 Book(s) to download [-] Error while login: <Response [400]>
> 
> <title>400 Bad Request</title>

I got the same error in img2pdf and the same when I use the new script

**Comment by 1i1i1i1i1i1i1** [comment]
Same error, the fix commit didn't work and I'm assuming that's because it's outdated now. Any other fix?
