### ISSUE TITLE
InvalidURL "no host supplied" error after successful loan, doesn't download

### ISSUE THREAD

**Issue by eggplantedd** [MiniGlome/Archive.org-Downloader#42]
```
Archive.org-Downloader-main>archive-org-downloader.py -e email -p password -u https://a
rchive.org/details/masteropticaltec0000deva -r 0
1 Book(s) to download
[+] Successful login
========================================
Current book: https://archive.org/details/masteropticaltec0000deva
[+] Successful loan
Traceback (most recent call last):
  File "Archive.org-Downloader-main\archive-org-downloader.py", line 209, in <module>
    title, links = get_book_infos(session, url)
  File "Archive.org-Downloader-main\archive-org-downloader.py", line 22, in get_book_infos
    response = session.get(infos_url)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line
 542, in get
    return self.request('GET', url, **kwargs)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line
 515, in request
    prep = self.prepare_request(req)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line
 443, in prepare_request
    p.prepare(
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 3
18, in prepare
    self.prepare_url(url, params)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 3
95, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
```

The URL for the file is https://archive.org/details/masteropticaltec0000deva

I had been using this program successfully for some time now, even downloading this file beforehand in jpeg form, so not sure what's changed- I got this error with the version I was using, then updated and found no difference.

Might I have uninstalled something required? I'm pretty sure I haven't since I last used it, just checking if it's that sort of mistake. I tried an extra slash at the end of the url, then left off the resolution flag- nothing.

I am on Windows 10 64 bit. The rest of the error is long and is attached. Thanks for any help!
[restoferror.txt](https://github.com/MiniGlome/Archive.org-Downloader/files/9126191/restoferror.txt)

**Comment by superpoincare** [comment]
Even I got this error just now! Was working till yesterday.

**Comment by MiniGlome** [comment]
It appears that there have been some changes in the archive.org backend and that the script is not working anymore, let me check.

**Comment by MiniGlome** [comment]
FIXED 👌
